# Generated by Django 2.0.6 on 2020-10-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('pic', models.ImageField(default='pic/11.jpg', upload_to='pic/')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 'drf_teacher',
            },
        ),
    ]
